// <auto-generated />
using System;
using GharKharchaAPI.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GharKharchaAPI.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312122338_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GharKharchaAPI.Data.Entities.BudgetEntity", b =>
                {
                    b.Property<int>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BudgetId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExpenseTypeId")
                        .HasColumnType("int");

                    b.Property<int>("FamilyId")
                        .HasColumnType("int");

                    b.Property<decimal>("LimitAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MonthYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BudgetId");

                    b.HasIndex("ExpenseTypeId");

                    b.HasIndex("FamilyId");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("GharKharchaAPI.Data.Entities.ExpenseEntity", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseId"));

                    b.Property<int>("AddedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpenseTypeId")
                        .HasColumnType("int");

                    b.Property<int>("FamilyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("ExpenseId");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("ExpenseTypeId");

                    b.HasIndex("FamilyId");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("GharKharchaAPI.Data.Entities.ExpenseTypeEntity", b =>
                {
                    b.Property<int>("ExpenseTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseTypeId"));

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExpenseTypeId");

                    b.ToTable("ExpenseTypes");

                    b.HasData(
                        new
                        {
                            ExpenseTypeId = 1,
                            ColorCode = "#FF6B6B",
                            Icon = "🛒",
                            IsDefault = true,
                            Name = "Food & Groceries"
                        },
                        new
                        {
                            ExpenseTypeId = 2,
                            ColorCode = "#4D96FF",
                            Icon = "🏠",
                            IsDefault = true,
                            Name = "Rent & EMI"
                        },
                        new
                        {
                            ExpenseTypeId = 3,
                            ColorCode = "#FFD93D",
                            Icon = "⛽",
                            IsDefault = true,
                            Name = "Transport"
                        },
                        new
                        {
                            ExpenseTypeId = 4,
                            ColorCode = "#6BCB77",
                            Icon = "⚡",
                            IsDefault = true,
                            Name = "Utilities"
                        },
                        new
                        {
                            ExpenseTypeId = 5,
                            ColorCode = "#A855F7",
                            Icon = "🎬",
                            IsDefault = true,
                            Name = "Entertainment"
                        },
                        new
                        {
                            ExpenseTypeId = 6,
                            ColorCode = "#FF6B6B",
                            Icon = "💊",
                            IsDefault = true,
                            Name = "Medical"
                        },
                        new
                        {
                            ExpenseTypeId = 7,
                            ColorCode = "#4D96FF",
                            Icon = "📚",
                            IsDefault = true,
                            Name = "Education"
                        },
                        new
                        {
                            ExpenseTypeId = 8,
                            ColorCode = "#FFD93D",
                            Icon = "🛍️",
                            IsDefault = true,
                            Name = "Shopping"
                        });
                });

            modelBuilder.Entity("GharKharchaAPI.Data.Entities.FamilyEntity", b =>
                {
                    b.Property<int>("FamilyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FamilyId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FamilyId");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("GharKharchaAPI.Data.Entities.RecurringExpenseEntity", b =>
                {
                    b.Property<int>("RecurringId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecurringId"));

                    b.Property<int>("AddedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ExpenseTypeId")
                        .HasColumnType("int");

                    b.Property<int>("FamilyId")
                        .HasColumnType("int");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NextDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecurringId");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("ExpenseTypeId");

                    b.HasIndex("FamilyId");

                    b.ToTable("RecurringExpenses");
                });

            modelBuilder.Entity("GharKharchaAPI.Data.Entities.UserEntity", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FamilyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("FamilyId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GharKharchaAPI.Data.Entities.BudgetEntity", b =>
                {
                    b.HasOne("GharKharchaAPI.Data.Entities.ExpenseTypeEntity", "ExpenseType")
                        .WithMany("Budgets")
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GharKharchaAPI.Data.Entities.FamilyEntity", "Family")
                        .WithMany("Budgets")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExpenseType");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("GharKharchaAPI.Data.Entities.ExpenseEntity", b =>
                {
                    b.HasOne("GharKharchaAPI.Data.Entities.UserEntity", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GharKharchaAPI.Data.Entities.ExpenseTypeEntity", "ExpenseType")
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GharKharchaAPI.Data.Entities.FamilyEntity", "Family")
                        .WithMany("Expenses")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GharKharchaAPI.Data.Entities.UserEntity", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AddedBy");

                    b.Navigation("ExpenseType");

                    b.Navigation("Family");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("GharKharchaAPI.Data.Entities.RecurringExpenseEntity", b =>
                {
                    b.HasOne("GharKharchaAPI.Data.Entities.UserEntity", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GharKharchaAPI.Data.Entities.ExpenseTypeEntity", "ExpenseType")
                        .WithMany()
                        .HasForeignKey("ExpenseTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GharKharchaAPI.Data.Entities.FamilyEntity", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddedBy");

                    b.Navigation("ExpenseType");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("GharKharchaAPI.Data.Entities.UserEntity", b =>
                {
                    b.HasOne("GharKharchaAPI.Data.Entities.FamilyEntity", "Family")
                        .WithMany("Members")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("GharKharchaAPI.Data.Entities.ExpenseTypeEntity", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("GharKharchaAPI.Data.Entities.FamilyEntity", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Expenses");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
